trigger: none

jobs:
  - job: android_build
    pool:
      vmImage: 'windows-2019'
      demands:
      - MSBuild
      - Xamarin.Android
      - JDK
    steps:
    - task: NuGetToolInstaller@0
      inputs:
        versionSpec: '5.4.0'
    - task: NuGetCommand@2
      inputs:
        restoreSolution: '.\mobile\Contoso.IoMT_Client\Contoso.IoMT_Client.sln'
    - task: XamarinAndroid@1
      inputs:
        projectFile: .\mobile\Contoso.IoMT_Client\Contoso.IoMT_Client\Contoso.IoMT_Client.Android\Contoso.IoMT_Client.Android.csproj
        outputDirectory: '$(Build.BinariesDirectory)/Release/Mobile'
        configuration: 'Release'
        clean: true
        msbuildVersionOption: latest
        msbuildArguments: '/p:JavaSdkDirectory="$(JAVA_HOME)/" '
    - task: AndroidSigning@3
      inputs:
        apkFiles: '**/*.apk'
        apksign: false
    - task: CopyFiles@2
      displayName: 'Copy Files'
      inputs:
        SourceFolder: '$(Build.BinariesDirectory)/Release/Mobile'
        Contents: '**/*.apk'
        TargetFolder: '$(Build.BinariesDirectory)/Release/Mobile/Staging'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.BinariesDirectory)/Release/Mobile/Staging'
        ArtifactName: 'drop-android'

  - job: ios_build
    pool:
      vmImage: 'macOS-10.15'
      demands:
      - xcode
      - Xamarin.iOS
    steps:
    - task: InstallAppleCertificate@2
      inputs:
        certSecureFile: $(certSecureFile)
        certPwd: $(certPwd)
    - task: InstallAppleProvisioningProfile@1
      inputs:
        provProfileSecureFile: $(provProfileSecureFile)
    - task: NuGetToolInstaller@0
      inputs:
        versionSpec: '5.4.0'
    - task: NuGetCommand@2
      inputs:
        restoreSolution: ./mobile/Contoso.IoMT_Client/Contoso.IoMT_Client.sln
    - task: XamariniOS@2
      inputs:
        solutionFile: ./mobile/Contoso.IoMT_Client/Contoso.IoMT_Client.sln
        buildForSimulator: false
        configuration: 'Release'
        packageApp: true
        signingProvisioningProfileID: '$(APPLE_PROV_PROFILE_UUID)'
        signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/*.ipa'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop-ios'
    - task: AppCenterDistribute@3
      inputs:
        serverEndpoint: 'App Center iOS Distribution'
        appSlug: 'WBA-H3/WBA-Client'
        appFile: '$(Build.ArtifactStagingDirectory)/**/*.ipa'
        releaseNotesOption: 'input'
        releaseNotesInput: 'Updated iOS client'
        destinationType: 'groups'