# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

trigger: none

jobs:
  - job: dotnet

    pool:
      vmImage: "windows-latest"

    steps:
      - task: UseDotNet@2
        displayName: "Install .NET Core"
        inputs:
          version: 3.1.x

      - task: DotNetCoreCLI@2
        displayName: "Build API"
        inputs:
          command: "build"
          arguments: --output ./out --configuration Release
          workingDirectory: ./backend/api

      - task: DotNetCoreCLI@2
        displayName: "Build CLI"
        inputs:
          command: "build"
          arguments: --output ./out --configuration Release
          workingDirectory: ./backend/cli

  - job: node

    pool:
      vmImage: "windows-latest"

    variables:
      npm_config_cache: $(Pipeline.Workspace)/.npm

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: "12.x"
      displayName: "Install Node.js"

    - task: Cache@2
      inputs:
        key: 'npm | "$(Agent.OS)" | ./backend/test/package-lock.json'
        restoreKeys: |
          npm | "$(Agent.OS)"
        path: $(npm_config_cache)
      displayName: "Cache npm packages"

    - script: npm ci
      workingDirectory: ./backend/test
      displayName: "Install dependencies"

    - script: npm run lint
      workingDirectory: ./backend/test
      displayName: "Run lint"
